server:
  port: 8088
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: API_SERVER
          uri: lb://API-SERVER
          predicates:
            - Path=/api/signin
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}
        - id: API_SERVER
          uri: lb://API-SERVER
          predicates:
            - Path=/api/signup
          filters:
            - RewritePath=/api/(?<path>.*),/$\{path}

        - id: API_SERVER
          uri: lb://API-SERVER
          predicates:
            - Path=/api/users/signin
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<path>.*),/$\{path}
            - name: AuthorizationHeaderFilter
jwt:
  secret:
    key: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
